apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynamic-application-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: crm.david-fred.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crm-frontend-service
            port:
              number: 80
  - host: api.david-fred.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crm-backend-service
            port:
              number: 5000